[package]
name = "task-manager"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.31", features = ["derive"] }
dotenv = "0.15.0"
dotenvy = "0.15.7"
postgres = "0.19.10"
serde = "1.0.218"
sqlx = "0.8.3"
tokio = "1.43.0"
